name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install Dependencies
        run: |
          poetry install

      - name: Run Linting
        run: |
          poetry run black --check src/ tests/

      - name: Run Tests
        run: |
          poetry run pytest

  publish:
    name: Publish to TestPyPI
    needs: test
    if: github.event_name == 'release'  # Runs only on GitHub Releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Build Package
        run: |
          poetry build

      - name: Publish to TestPyPI
        env:
          TEST_PYPI_USERNAME: __token__
          TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/simple/
          poetry config pypi-token.test-pypi $TEST_PYPI_PASSWORD
          poetry publish -r test-pypi
